//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeBrainDesktopApp.SQLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class AllProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AllProduct()
        {
            this.Additions = new HashSet<Addition>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ProductAdditionsIDs = new HashSet<ProductAdditionsID>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Price { get; set; }
        public Nullable<bool> New { get; set; }
        public int CategoryID { get; set; }
    
       [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Addition> Additions { get; set; }
        public virtual Category Category { get; set; }
       [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
       [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAdditionsID> ProductAdditionsIDs { get; set; }
    }
}
