//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeBrainDesktopApp.SQLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int id { get; set; }
        public int Count { get; set; }
        public System.DateTime DateTime { get; set; }
        public int AllProductID { get; set; }
        public int EnployeeID { get; set; }
    
        public virtual AllProduct AllProduct { get; set; }
        public virtual Enployee Enployee { get; set; }
    }
}
